### ISSUE TITLE
Cannot install skater with BRLC from MacOS

### ISSUE THREAD

**Issue by snthibaud** [oracle/Skater#302]
I am unable to get the Bayesian Rule List classifier to work from MacOS so far. I tried:
- Installing skater with conda -> latest version does not include BRLC
- Installing with pip using `sudo pip install -U --no-deps --force-reinstall --install-option="--rl=True" skater==1.1.2` -> I get:
```
      File "/opt/anaconda3/envs/skater/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['bash', '/private/var/folders/sb/l953ckxx4v3ds19bcb9n6q400000gr/T/pip-install-qt4_g4a7/skater/setup.sh', 'linux-ubuntu']' returned non-zero exit status 1.
```
It seems that the pip-install refers to `ubuntu`, so perhaps MacOS is not supported?

I also installed skater with `pip` without any extra options (ensuring Python version <= 3.6, because higher is not supported). That install did work, but when using BRLC, the `sbrl` R package could not be found.
Trying to install it from R resulted in:
```
Warning in install.packages :
  package ‘sbrl’ is not available (for R version 3.6.3)
```
Any suggestions?

**Comment by snthibaud** [comment]
I tried to install it on Ubuntu in a virtual machine - and even then I get:

```
   * installing to library ‘/usr/local/lib/R/site-library’                             
    * installing *source* package ‘arules’ ...                                          
    ** package ‘arules’ successfully unpacked and MD5 sums checked                      
    ** using staged installation                                                        
    ** libs                                                                             
    installing to /usr/local/lib/R/site-library/00LOCK-arules/00new/arules/libs         
    ** R                                                                                
    ** data                                                                             
    ** inst                                                                             
    ** byte-compile and prepare package for lazy loading                                
    ** help                                                                             
    *** installing help indices                                                         
    ** building package indices                                                         
    ** installing vignettes                                                             
    ** testing if installed package can be loaded from temporary location               
    ** checking absolute paths in shared objects and dynamic libraries                  
    ** testing if installed package can be loaded from final location                   
    ** testing if installed package keeps a record of temporary installation path       
    * DONE (arules)                                                                     
    --2020-05-07 15:45:22--  https://cran.r-project.org/src/contrib/sbrl_1.2.tar.gz     
    Resolving cran.r-project.org (cran.r-project.org)... 137.208.57.37                  
    Connecting to cran.r-project.org (cran.r-project.org)|137.208.57.37|:443... connected.                                                                                      
    HTTP request sent, awaiting response... 404 Not Found                               
    2020-05-07 15:45:23 ERROR 404: Not Found.                                           
                                                                                        
    Warning: invalid package ‘sbrl_1.2.tar.gz’                                          
    Error: ERROR: no packages specified                                                 
    Traceback (most recent call last):                                                  
      File "<string>", line 1, in <module>                                              
      File "/tmp/pip-install-oue_hpcg/skater/setup.py", line 97, in <module>
        setup_package()
      File "/tmp/pip-install-oue_hpcg/skater/setup.py", line 66, in setup_package
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-oue_hpcg/skater/setup.py", line 39, in run
        subprocess.check_output(['bash', shell_script_path, self.ostype])
      File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['bash', '/tmp/pip-install-oue_hpcg/skater/setup.sh', 'linux-ubuntu']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oue_hpcg/skater/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oue_hpcg/skater/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-44mqjm73/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/skater --rl=True Check the logs for full command output.
```
Perhaps the install steps in the README are outdated?

**Comment by snthibaud** [comment]
On Ubuntu 18.04 the install just hangs (using both methods of the readme).

**Comment by aliceschi93** [comment]
I'm not being able to use TreeSurrogate and BRLC on jupyter with anaconda in win64. Does anyone know how to install the complete skater package in windows?

**Comment by alyshav** [comment]
This has worked for me: pip install git+https://github.com/oracle/Skater.git. I found it here: https://github.com/oracle/Skater/issues/287#issuecomment-682358821
